#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="k")]
	public partial class MyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertactor(actor instance);
    partial void Updateactor(actor instance);
    partial void Deleteactor(actor instance);
    partial void Insertactorsfilm(actorsfilm instance);
    partial void Updateactorsfilm(actorsfilm instance);
    partial void Deleteactorsfilm(actorsfilm instance);
    partial void Insertfilm(film instance);
    partial void Updatefilm(film instance);
    partial void Deletefilm(film instance);
    #endregion
		
		public MyDataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.kConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<actor> actors
		{
			get
			{
				return this.GetTable<actor>();
			}
		}
		
		public System.Data.Linq.Table<actorsfilm> actorsfilms
		{
			get
			{
				return this.GetTable<actorsfilm>();
			}
		}
		
		public System.Data.Linq.Table<film> films
		{
			get
			{
				return this.GetTable<film>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.actors")]
	public partial class actor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _a_id;
		
		private string @__name;
		
		private System.Nullable<System.DateTime> @__birthdate;
		
		private string @__state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ona_idChanging(int value);
    partial void Ona_idChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_birthdateChanging(System.Nullable<System.DateTime> value);
    partial void On_birthdateChanged();
    partial void On_stateChanging(string value);
    partial void On_stateChanged();
    #endregion
		
		public actor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int a_id
		{
			get
			{
				return this._a_id;
			}
			set
			{
				if ((this._a_id != value))
				{
					this.Ona_idChanging(value);
					this.SendPropertyChanging();
					this._a_id = value;
					this.SendPropertyChanged("a_id");
					this.Ona_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="VarChar(20)")]
		public string _name
		{
			get
			{
				return this.@__name;
			}
			set
			{
				if ((this.@__name != value))
				{
					this.On_nameChanging(value);
					this.SendPropertyChanging();
					this.@__name = value;
					this.SendPropertyChanged("_name");
					this.On_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_birthdate]", Storage="__birthdate", DbType="Date")]
		public System.Nullable<System.DateTime> _birthdate
		{
			get
			{
				return this.@__birthdate;
			}
			set
			{
				if ((this.@__birthdate != value))
				{
					this.On_birthdateChanging(value);
					this.SendPropertyChanging();
					this.@__birthdate = value;
					this.SendPropertyChanged("_birthdate");
					this.On_birthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_state]", Storage="__state", DbType="VarChar(20)")]
		public string _state
		{
			get
			{
				return this.@__state;
			}
			set
			{
				if ((this.@__state != value))
				{
					this.On_stateChanging(value);
					this.SendPropertyChanging();
					this.@__state = value;
					this.SendPropertyChanged("_state");
					this.On_stateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.actorsfilms")]
	public partial class actorsfilm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _a_id;
		
		private int _f_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ona_idChanging(int value);
    partial void Ona_idChanged();
    partial void Onf_idChanging(int value);
    partial void Onf_idChanged();
    #endregion
		
		public actorsfilm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int a_id
		{
			get
			{
				return this._a_id;
			}
			set
			{
				if ((this._a_id != value))
				{
					this.Ona_idChanging(value);
					this.SendPropertyChanging();
					this._a_id = value;
					this.SendPropertyChanged("a_id");
					this.Ona_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int f_id
		{
			get
			{
				return this._f_id;
			}
			set
			{
				if ((this._f_id != value))
				{
					this.Onf_idChanging(value);
					this.SendPropertyChanging();
					this._f_id = value;
					this.SendPropertyChanged("f_id");
					this.Onf_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.film")]
	public partial class film : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _f_id;
		
		private string @__film;
		
		private System.Nullable<System.DateTime> @__relise;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onf_idChanging(int value);
    partial void Onf_idChanged();
    partial void On_filmChanging(string value);
    partial void On_filmChanged();
    partial void On_reliseChanging(System.Nullable<System.DateTime> value);
    partial void On_reliseChanged();
    #endregion
		
		public film()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int f_id
		{
			get
			{
				return this._f_id;
			}
			set
			{
				if ((this._f_id != value))
				{
					this.Onf_idChanging(value);
					this.SendPropertyChanging();
					this._f_id = value;
					this.SendPropertyChanged("f_id");
					this.Onf_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_film]", Storage="__film", DbType="VarChar(20)")]
		public string _film
		{
			get
			{
				return this.@__film;
			}
			set
			{
				if ((this.@__film != value))
				{
					this.On_filmChanging(value);
					this.SendPropertyChanging();
					this.@__film = value;
					this.SendPropertyChanged("_film");
					this.On_filmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_relise]", Storage="__relise", DbType="Date")]
		public System.Nullable<System.DateTime> _relise
		{
			get
			{
				return this.@__relise;
			}
			set
			{
				if ((this.@__relise != value))
				{
					this.On_reliseChanging(value);
					this.SendPropertyChanging();
					this.@__relise = value;
					this.SendPropertyChanged("_relise");
					this.On_reliseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
